import './globals.scss'
import styles from './layout.module.scss'
import type { Metadata } from 'next'
import Navbar from './components/Navbar/Navbar'
import Topbar from './components/Topbar/Topbar'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={styles.body}>
        <Topbar />
        <main className={styles.main}>
          {children}
        </main>
      </body>
    </html>
  )
}
